---
title: "Behavior Minimization"
author: "Mariano Cerrutti"
date: "5/26/2020"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      results= "asis")
#install.packages("dplyr")
#install.packages("magrittr")
#install.packages("ggplot2")
#install.packages("jsonlite")
#install.packages("plot3D")
library(dplyr)
library(magrittr)
library(ggplot2)
library(jsonlite)
library(gridExtra)
library(grid)
library(lattice)
library(knitr)
library(scales)
library(plot3D)
library(stringr)
suppressMessages(library(dplyr))
suppressMessages(library(ggplot2))
#experimental_composite <- read.csv(file='/home/mariano/code/henos-automata/doc/experimental_setting/tmp_results/general_data_composite.csv')
experimental_composite <- read.csv(file='/home/mariano/code/henos-automata/doc/experimental_setting/tmp_results/unrealizable_data_composite.csv')
genbuf_missing <- subset(experimental_composite, grepl("automaton_missing_assumption", name, fixed=TRUE))
genbuf_removed <- subset(experimental_composite, grepl("automaton_removed_env_safety", name, fixed=TRUE))
collector_missing <- subset(experimental_composite, grepl("v1_missing_assumption", name, fixed=TRUE))
robot_samples <- subset(experimental_composite, grepl("robot", name, fixed=TRUE))

```
<style type="text/css">
.twoC {width: 100%}
.clearer {clear: both}
.twoC .table {max-width: 50%; float: right}
.twoC img {max-width: 50%; float: left}
table {
  margin: auto;
  border-top: 1px solid #666;
  border-bottom: 1px solid #666;
}
table thead th { border-bottom: 1px solid #ddd; }
th, td { padding: 5px; }
thead, tfoot, tr:nth-child(even) { background: #eee; }
pre{display:none;}
</style>

## Minimization progression
<div class="twoC">
```{r echo=FALSE}
steps_path = "/home/mariano/code/henos-automata/doc/experimental_setting/tmp_results/steps/"
steps_files = list.files(path=steps_path, pattern="*.csv")
#for (i in 1:length(steps_files)) steps_df[i] <- read.csv(steps_files[i])

effective_plots <- 0
for (i in 1:length(steps_files)){
  df <- read.csv(file=paste(steps_path, steps_files[i], sep=''))
  if(length(df$step) < 2){
    next
  }
  effective_plots <- effective_plots + 1
}
#layout(matrix(1:effective_plots*2,nc=2, nr= effective_plots,byr=T))
for (i in 1:length(steps_files)){
  df <- read.csv(file=paste(steps_path, steps_files[i], sep=''))
  if(length(df$step) < 2){
    next
  }
  df = df[-1,]
  time_plot <- ggplot(df, aes(x=step, y=time, group=i)) +
  geom_line(linetype="dashed", color="blue", size=1.2)+
  geom_point(color="red", size=3) + 
  labs(title=steps_files[i]) +
	xlab("Steps") +
	ylab("Time (s)") 
  print(time_plot)
  size_plot <- ggplot(df, aes(x=step, y=size, group=i)) +
  geom_line(linetype="dashed", color="blue", size=1.2)+
  geom_point(color="red", size=3) + 
  labs(title=steps_files[i]) +
	xlab("Steps") +
	ylab(expression(paste("|",Delta[paste("E","'")],"|")))
  print(size_plot)  
}


```
</div>
<div class="clearer"></div>
